# Simple Plymouth script that shows text
Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

message_sprite = Sprite();
message_sprite.SetPosition(Window.GetX() + Window.GetWidth() / 2, Window.GetHeight() / 2, 10000);

fun message_callback(text) {
    my_image = Image.Text(text, 1, 1, 1);
    message_sprite.SetImage(my_image);
    message_sprite.SetX(Window.GetWidth() / 2 - my_image.GetWidth() / 2);
    message_sprite.SetY(Window.GetHeight() / 2 - my_image.GetHeight() / 2);
}

Plymouth.SetMessageFunction(message_callback);

fun refresh_callback() {
    message_callback("Booting...");
}

Plymouth.SetRefreshFunction(refresh_callback);
